name: Idle
options:
  bundleIdPrefix: com.idle
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown"
    SWIFT_VERSION: "5.0"
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

targets:
  Idle:
    type: application
    platform: iOS
    sources:
      - path: Idle
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.idle.app
        INFOPLIST_KEY_CFBundleDisplayName: Idle
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.healthcare-fitness"
    info:
      path: Idle/Info.plist
      properties:
        UIBackgroundModes:
          - audio
        UIRequiresFullScreen: true
        ITSAppUsesNonExemptEncryption: false
        UIAppFonts:
          - IBMPlexMono-Regular.ttf
